server:
  port: 8082
  
spring:
  application:
    name: apigateway

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8081/eureka/
    instance:
    hostname: localhost
     
  cloud:
    gateway:
      routes:
      - id: :JOBPORTAL
        uri: http://localhost:8080/
        predicates:
        - path =/api/auth/**,/api/auth/forgotPassword/**,/api/recruiter/**,
                /api/recruiter/getJobById/**,/api/recruiter/deleteJob/**,
                /api/recruiter/updateJob/**,/api/recruiter/getCandidateByJobId/**,
                /api/recruiter/getCandidateById/**,
                /api/user/**,/api/user/checkAppliedJob/**,
                
        
